version : '2'

services:

  mongodb:
    image: mongo
    container_name: vocabdb
    ports:
      - "27020:27017" # MongoDB clients can connect to this instance on 27020
                      # leaving 27017 free for another instance hosted on the
                      # host.
    environment:
      MONGO_DBNAME: vocabulary
    volumes:
      - 'mongo:/data/db'

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

  vocabulary-service:
    build : .
    depends_on:
      - "mongodb"
    ports:
      - "8080:8080"
    environment:
      MONGO_DBNAME: vocabulary

volumes:
  mongo: